#ifndef GAME_ENGINE_FEATURE_SWITCH_VK_H
#define GAME_ENGINE_FEATURE_SWITCH_VK_H

//#define USE_VARIABLE_SHADING_RATE_TIER2 0
#define USE_REVERSEZ_PERSPECTIVE_SHADOW 1

// this should be in another file
#define ENABLE_PBR                      1


#endif  // GAME_ENGINE_FEATURE_SWITCH_VK_H