#ifndef GAME_ENGINE_PROFILER_CONFIG_H
#define GAME_ENGINE_PROFILER_CONFIG_H

#ifdef GAME_ENGINE_USE_TRACY_GPU_PROFILING
#ifdef GAME_ENGINE_FORCE_VULKAN
#define GAME_ENGINE_TRACY_GPU_PROFILING_VK
#elif defined(GAME_ENGINE_FORCE_DIRECTX)
#define GAME_ENGINE_TRACY_GPU_PROFILING_DX12
#else
#error "Tracy GPU profiling requires FORCE_RHI_API to be enabled. Please set FORCE_RHI_API=ON in cmake and select specific API."
#endif
#endif

#endif  // GAME_ENGINE_PROFILER_CONFIG_H