#ifndef GAME_ENGINE_PROFILER_CONFIG_H
#define GAME_ENGINE_PROFILER_CONFIG_H

//#if defined(GAME_ENGINE_USE_PROFILING) && defined(GAME_ENGINE_USE_CPU_PROFILING) && defined(GAME_ENGINE_USE_TRACY)
//#define PROFILER_CPU_ENABLED
//#endif
//
//#if defined(GAME_ENGINE_USE_PROFILING) && defined(GAME_ENGINE_USE_GPU_PROFILING) && defined(TRACY_ENABLE)
//#define PROFILER_GPU_TRACY_ENABLED
//
//#ifdef GAME_ENGINE_USE_DX12
//#define PROFILER_GPU_DX12_ENABLED
//#endif
//
//#ifdef GAME_ENGINE_USE_VULKAN
//#define PROFILER_GPU_VK_ENABLED
//#endif
//#endif

#ifdef GAME_ENGINE_USE_TRACY_GPU_PROFILING
#ifdef GAME_ENGINE_FORCE_VULKAN
#define GAME_ENGINE_TRACY_GPU_PROFILING_VK
#elif defined(GAME_ENGINE_FORCE_DIRECTX)
#define GAME_ENGINE_TRACY_GPU_PROFILING_DX12
#else
#error "Tracy GPU profiling requires FORCE_RHI_API to be enabled. Please set FORCE_RHI_API=ON in cmake and select specific API."
#endif
#endif

#endif  // GAME_ENGINE_PROFILER_CONFIG_H